### ISSUE TITLE
Broken responsive design

### ISSUE THREAD

**Issue by interduo** [Cacti/plugin_monitor#104]
**Describe the bug**
Two shorts group are not in the same line as year earlier.

**To Reproduce**
Just run monitor.php and choose 'grouping = groups' and view = "default" (icons+text) or (tiles+time)

**Expected behavior**
Two shorts group are in the same line. 
We expecting to have compact design to see all (as much as it's possible) hosts in monitor.

**Screenshots**
![rest](https://user-images.githubusercontent.com/17087236/54022661-4a0ee980-4193-11e9-8de6-2580711424a8.png)

**Plugin (please complete the following information):**
 - Version: [git]
 - Source: [github]
 - Identifer: [orgin/develop, updated dialy]

**Desktop (please complete the following information):**
 - OS: [Linux Ubuntu 18.10]
 - Browser [Chromium]
 - Version [71.0.3578.98]

**Additional context**
There is a waste of free space.

**Comment by interduo** [comment]
I don't know is this connected but there is another little/small issue with this:
![cacti-no-margin](https://user-images.githubusercontent.com/17087236/54031352-cc58d700-41ae-11e9-8e21-05d7743ea9f7.png)

There is no margin at the bottom and seems that the scrolls at the top and at the bottom are cut off.

**Comment by cigamit** [comment]
This should all be resolved now.

**Comment by interduo** [comment]
I did update to newest origin/develop. The issue isn't resolved.
Now - there are always one group per line (Grouping: Tree view).

We awaits to have more than one group in line if there is space.

Please reopen.

**Comment by netniV** [comment]
The latest update does seem to change the styling/layout of the non-default `Grouping` filter.  All items are now centralised with no header colors showing the change of groups.

**Comment by interduo** [comment]
This change should be applied also when there is many sites with few hosts. Few sites could be also in one line.

**Comment by TheWitness** [comment]
If anyone wants to volunteer a fix, I'm all in.
